#pragma once

#include <optick.h>

#define YL_ENABLE_PROFILING 1

#if YL_ENABLE_PROFILING
#define YL_PROFILE_FRAME(...) OPTICK_FRAME(__VA_ARGS__)
#define YL_PROFILE_FUNCTION(...)  OPTICK_EVENT(__VA_ARGS__)
#define YL_PROFILE_TAG(NAME, ...) OPTICK_TAG(NAME, __VA_ARGS__)
#define YL_PROFILE_SCOPE(NAME) OPTICK_EVENT_DYNAMIC(NAME)
#define YL_PROFILE_THREAD(...) OPTICK_THREAD(__VA_ARGS__)
#define YL_PROFILE_CATEGORY(...) OPTICK_CATEGORY(__VA_ARGS__)
#else
#define YL_PROFILE_FRAME(...)
#define YL_PROFILE_FUNCTION(...)
#define YL_PROFILE_TAG(NAME, ...)
#define YL_PROFILE_SCOPE(NAME)
#define YL_PROFILE_THREAD(...)
#endif